services:
  aerospike:
    image: aerospike/aerospike-server
    container_name: aerospike
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
  kion:
    build: .
    ports:
      - "8080:8080"
    links:
      - aerospike
    depends_on:
      aerospike:
        condition: service_started