services:
  aerospike:
    image: aerospike/aerospike-server
    container_name: aerospike
    ports:
      - "3000:3000"
  kion:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      aerospike:
        condition: service_started