version: '2'

services:
  aerospike:
    hostname: aerospike
    container_name: aerospike
    image: aerospike/aerospike-server
  kion:
    build: .
    ports:
      - "8080:8080"
    links:
      - aerospike
    depends_on:
      aerospike:
        condition: service_started